### ISSUE TITLE
Add necessary comments to the code

### ISSUE THREAD

**Issue by chavi362** [hetulbhatt/KeyFlow#39]
I would be happy to write comments to the code in the project files so that the code is more readable and understandable to other programmers.
@hetulbhatt , please assign it to me

**Comment by hetulbhatt** [comment]
Assigned to you.

**Comment by chavi362** [comment]
I did it!! please merge my pull request...

**Comment by hetulbhatt** [comment]
Thanks @chavi362. I have been away for a couple of days from my desk, will try to review PR tomorrow or day after tomorrow.

**Comment by chavi362** [comment]
Thanks!
Enjoy your vacation!

‫בתאריך יום ג׳, 5 בספט׳ 2023 ב-20:33 מאת ‪Hetul Bhatt‬‏ <‪
***@***.***‬‏>:‬

**Comment by hetulbhatt** [comment]
@chavi362, I have reviewed the PR and provided some comments. Please have a look here: https://github.com/hetulbhatt/KeyFlow/pull/44#pullrequestreview-1617998364

**Comment by chavi362** [comment]
Thank you!
I'll work about it tomorrow

‫בתאריך יום ו׳, 8 בספט׳ 2023 ב-21:16 מאת ‪Hetul Bhatt‬‏ <‪
***@***.***‬‏>:‬

**Comment by hetulbhatt** [comment]
Thanks, @chavi362 for working on this issue!
